export const CUSTOMER_SEED = [
  {
    name: "Rohit Rajawat",
    username: "admin-yoga",
    email: "myofficialrsr@gmail.com",
    country: "IN",
    city: "Alwar",
    state: "RJ",
    postcode: "301708",
    dateRegistered: new Date("2023-05-25T08:52:50"),
    lastActive: new Date("2023-06-22T11:28:54"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "rohit rajasway",
    username: "null",
    email: "sdcds2rf@dsf.in",
    country: "AE",
    city: "rrff",
    state: "null",
    postcode: "null",
    dateRegistered: null,
    lastActive: new Date("2023-06-20T15:46:29"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "Nikita Thanwani",
    username: "null",
    email: "neatbynicky@gmail.com",
    country: "AE",
    city: "Dubai",
    state: "null",
    postcode: "null",
    dateRegistered: null,
    lastActive: new Date("2023-06-21T07:55:15"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "jkj jkjl",
    username: "null",
    email: "cvb@ghg.com",
    country: "AE",
    city: "ffxsg",
    state: "null",
    postcode: "null",
    dateRegistered: null,
    lastActive: new Date("2023-06-20T17:52:50"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "Rohit Rajawat",
    username: "null",
    email: "myofficialrsr@gmail.com",
    country: "IN",
    city: "Alwar",
    state: "RJ",
    postcode: "301708",
    dateRegistered: null,
    lastActive: new Date("2023-06-20T19:13:03"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "test Testing",
    username: "null",
    email: "abc@gmail.com",
    country: "AE",
    city: "abu dhabi",
    state: "null",
    postcode: "null",
    dateRegistered: null,
    lastActive: new Date("2023-06-21T04:41:01"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "genphcy",
    email: "genphcy@bmaill.xyz",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2023-11-14T04:15:37"),
    lastActive: new Date("2023-11-14T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "kaylenebatts7347",
    email: "kaylenebatts7347@1secmail.org",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2023-11-21T20:55:28"),
    lastActive: null,
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "Hamda Al Shamsi",
    username: "null",
    email: "h_al_shamsi@hotmail.com",
    country: "AE",
    city: "Dubai",
    state: "null",
    postcode: "null",
    dateRegistered: null,
    lastActive: new Date("2023-11-30T11:14:26"),
    lastOrder: new Date("2023-11-30T11:14:26"),
    ordersCount: 1,
    totalSpend: "694.00",
    averageOrderValue: "694.00",
  },
  {
    name: "null",
    username: "hz_philematium_sanctus",
    email: "hz_philematium_sanctus@tb-ndfl1.ru",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2023-12-02T05:19:25"),
    lastActive: new Date("2023-12-02T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "hermanspedding2449",
    email: "hermanspedding2449@1secmail.net",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2023-12-15T11:31:13"),
    lastActive: new Date("2023-12-15T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "margaritaledesma",
    email: "margaritaledesma@1secmail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-01-18T03:20:56"),
    lastActive: new Date("2024-01-18T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "dl.g.ki.h.mz.osb",
    email: "dl.g.ki.h.mz.osb@gmail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-01-27T18:46:58"),
    lastActive: new Date("2024-01-27T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "kasharhoades2882",
    email: "kasharhoades2882@1mail.x24hr.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-03-02T00:53:16"),
    lastActive: new Date("2024-03-02T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "nikita thanwani",
    username: "null",
    email: "nikitat2291@hotmail.com",
    country: "AE",
    city: "Dubai",
    state: "null",
    postcode: "null",
    dateRegistered: null,
    lastActive: new Date("2024-03-11T07:04:27"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "zainab hassan",
    username: "null",
    email: "xeneb.naqvi@gmail.com",
    country: "AE",
    city: "Dubai",
    state: "Dubai",
    postcode: "null",
    dateRegistered: null,
    lastActive: new Date("2024-03-11T10:26:16"),
    lastOrder: new Date("2024-03-11T10:26:16"),
    ordersCount: 1,
    totalSpend: "230.00",
    averageOrderValue: "230.00",
  },
  {
    name: "null",
    username: "mogantyouhou1983",
    email: "mogantyouhou1983@bushka345.store",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-03-26T18:42:48"),
    lastActive: new Date("2024-03-26T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "esinansa1979",
    email: "esinansa1979@raiz-pr.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-04-22T18:50:34"),
    lastActive: new Date("2024-04-22T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "eyeoafgp",
    email: "eyeoafgp@mailkv.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-09-03T17:32:09"),
    lastActive: new Date("2024-09-03T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "mhw99",
    email: "mhw99@icloud.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-09-27T07:49:27"),
    lastActive: null,
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "phyllisschiller",
    email: "phyllisschiller@dcctb.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-11-24T10:50:17"),
    lastActive: new Date("2024-11-24T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "leathawhittle5512",
    email: "leathawhittle5512@dvd.dns-cloud.net",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2024-11-24T11:12:24"),
    lastActive: new Date("2024-11-24T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "geraldcarranza6058",
    email: "geraldcarranza6058@1secmail.net",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-02-14T07:35:20"),
    lastActive: new Date("2025-02-14T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "nexqoon",
    email: "nexqoon@gmail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-02-20T14:38:17"),
    lastActive: new Date("2025-02-20T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "jimmyhennessy5408",
    email: "jimmyhennessy5408@1secmail.org",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-02-22T05:52:46"),
    lastActive: new Date("2025-02-22T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "annettegoldschmidt5117",
    email: "annettegoldschmidt5117@kzccv.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-03-05T20:29:43"),
    lastActive: new Date("2025-03-05T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "fidelstiles",
    email: "fidelstiles@mailcatch.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-03-18T22:18:09"),
    lastActive: new Date("2025-03-18T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "a.dr.i.an.aa.nd.r.es.de.n.n.i.s",
    email: "a.dr.i.an.aa.nd.r.es.de.n.n.i.s@gmail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-04-01T15:32:27"),
    lastActive: new Date("2025-04-01T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "night",
    email: "night@prostpro.fun",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-04-04T08:35:47"),
    lastActive: new Date("2025-04-04T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "qrnogzzx",
    email: "qrnogzzx@maillv.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-08-02T07:34:56"),
    lastActive: new Date("2025-08-02T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "info209",
    email: "info209@noreply0.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-08-05T07:56:49"),
    lastActive: new Date("2025-08-05T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "ptlwauue",
    email: "ptlwauue@znemail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-09-03T08:02:20"),
    lastActive: new Date("2025-09-03T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "nicumomoloaca3",
    email: "nicumomoloaca3@gmail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-10-31T13:46:15"),
    lastActive: new Date("2025-10-31T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "rickragan6825",
    email: "rickragan6825@spambog.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-11-03T05:23:03"),
    lastActive: new Date("2025-11-03T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "antun.murkovic",
    email: "antun.murkovic@alvi.cc",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-11-03T15:59:37"),
    lastActive: new Date("2025-11-03T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "gtcrseir",
    email: "gtcrseir@znemail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-11-08T01:55:23"),
    lastActive: new Date("2025-11-08T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "kasha.hays.8533",
    email: "kasha.hays.8533@poochta.ru",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-11-30T05:31:21"),
    lastActive: new Date("2025-11-30T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "victorina.jamison-5464",
    email: "victorina.jamison-5464@poochta.ru",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-12-04T03:09:49"),
    lastActive: new Date("2025-12-04T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "fredpost",
    email: "fredpost@spacemaiil.ru",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2025-12-07T19:11:20"),
    lastActive: new Date("2025-12-07T00:00:00"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "tolgacan",
    email: "tolgacan@em2.thematinggrounds.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-01-31T11:18:33"),
    lastActive: new Date("2026-01-31T11:18:45"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "johntaylor6574u7tt",
    email: "johntaylor6574u7tt@b.travel-e-store.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-02-15T17:00:42"),
    lastActive: new Date("2026-02-15T17:00:50"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "robertanderson3441yrih",
    email: "robertanderson3441yrih@c.budgetthailandtravel.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-03-26T22:34:34"),
    lastActive: new Date("2026-03-26T22:34:43"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "hassanbyrne685629acv",
    email: "hassanbyrne685629acv@a.seoautomationpro.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-03-27T01:45:44"),
    lastActive: new Date("2026-03-27T01:45:53"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "huiesposito49272",
    email: "huiesposito49272@a.seoautomationpro.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-03-28T08:47:36"),
    lastActive: new Date("2026-03-28T08:47:52"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "jennifertaylor4124ci3y",
    email: "jennifertaylor4124ci3y@f.seoautomationpro.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-04-01T11:22:38"),
    lastActive: new Date("2026-04-01T11:22:48"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "kirill2001",
    email: "kirill2001@casinotds.xyz",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-04-01T16:42:24"),
    lastActive: new Date("2026-04-01T16:42:34"),
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
  {
    name: "null",
    username: "k.oz.a.x.a.l.i.521",
    email: "k.oz.a.x.a.l.i.521@gmail.com",
    country: "null",
    city: "null",
    state: "null",
    postcode: "null",
    dateRegistered: new Date("2026-07-08T09:37:20"),
    lastActive: null,
    lastOrder: null,
    ordersCount: 0,
    totalSpend: "0.00",
    averageOrderValue: "0.00",
  },
] as const;
